### ISSUE TITLE
Link to results on ohsome.org/apps/dashboard

### ISSUE THREAD

**Issue by tordans** [GIScience/ohsome-dashboard#2]
It would be great to be able to copy the link to a result on https://ohsome.org/apps/dashboard/.

Right now, in order to share a result, I need to send a step-by-step-tutorial how to re-produce it or send a static screenshot.

**Comment by tyrasd** [comment]
Permalinks are now implemented in the dashboard ([example](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=none&time=2007-10-08T00%3A00%3A00Z%2F2023-06-25T21%3A00Z%2FP1M&measure=count&filter=type%3Anode+and+amenity%3Ddrinking_water&bboxes=12.8954118%2C52.2769394%2C13.817763%2C52.7148926)). In the UI it is available in the result log:

<img src="https://github.com/GIScience/ohsome-dashboard/assets/1927298/f05e6384-e70f-4efc-aa6b-a9d46f9499c8" width="300">
