### ISSUE TITLE
When requested counts of an element show the actual real amount

### ISSUE THREAD

**Issue by jjiglesiasg** [GIScience/ohsome-dashboard#30]
When requested counts of an element instead of showing the data in rounded numbers (ie 304K) show the actual REAL amount (ie 304625)

OSM-Analytics showed actual numbers and was quite handy to control statistics by the number and not rounded

Thanks

**Comment by Hagellach37** [comment]
Hey @jjiglesiasg,
thanks for reaching out here and suggesting this improvement. We have discussed this today with the developer team.

Especially if the numbers get large, e.g. into millions, rounded numbers were an approach to keep the dashboard clean. But, we think that we might be able to add a hover on the big number to show the actual real value as well.

Besides this there is also already the option to download the results either in `json` or `csv` format. In these files you will find the actual real numbers and not the rounded ones. So for your monitoring or reporting you might want to use these files as well.

**Comment by jjiglesiasg** [comment]
Hi, I did download the json and csv data for Buildings in my country, the graphic data shows 304K however the csv file shows the funny number of: 

timestamp | value
2023-10-08T00:00:00Z | 411488086.2

I mean 411 Million buildings? Really?


How you can see the count give you a "weird" value at least in the csv fine. Totally unrealistic.

**Comment by jjiglesiasg** [comment]
With you have the same consult for several areas for example (Countries, States, Departments, Counties, etc) downloading a csv file for each query result in a nightmare of files all to be renamed from result.csv.
The hover actual real data show seems to be more practical and quicker, if that could be implemented ASAP will be great.
Thanks and BsRgds

**Comment by tyrasd** [comment]
for multiple areas, you can do the following: select all the individual areas on the map such that they are all highlighted in blue, and then choose the option `boundary` in the setting for `Group Results By …`. Then the result graph and exported csv will contain all regions simultaneously. Example:

![image](https://github.com/GIScience/ohsome-dashboard/assets/1927298/d56b943a-2f5a-458b-b11c-cf05f8107260)

**Comment by tyrasd** [comment]
> How you can see the count give you a "weird" value at least in the csv fine. Totally unrealistic.

I tried this out just now and cannot reproduce the issue. The numbers in the exported csv should always match the graph and summary table displayed in the dashboard (see below). Are you sure you selected the correct graph when exporting the csv file? Because it also contains a number with a decimal point, which should never be the case for `count` results, and is instead only present in queries which are using the `length`, `perimeter` or `area` measure.

<hr>

Results for `type:way and building=*` in Bolivia in exported CSV:

```csv
…
2023-07-08T00:00:00Z,292460
2023-08-08T00:00:00Z,292876
2023-09-08T00:00:00Z,295850
2023-10-08T00:00:00Z,304288
2023-11-08T00:00:00Z,321434
2023-12-08T00:00:00Z,341881
```

**Comment by jjiglesiasg** [comment]
> for multiple areas, you can do the following: select all the individual areas on the map such that they are all highlighted in blue, and then choose the option `boundary` in the setting for `Group Results By …`. Then the result graph and exported csv will contain all regions simultaneously. Example:
> 
> ![image](https://private-user-images.githubusercontent.com/1927298/298027512-d56b943a-2f5a-458b-b11c-cf05f8107260.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzU3OTgsIm5iZiI6MTcwNTc3NTQ5OCwicGF0aCI6Ii8xOTI3Mjk4LzI5ODAyNzUxMi1kNTZiOTQzYS0yZjVhLTQ1OGItYjExYy1jZjA1ZjgxMDcyNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMTgzMTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTMyZGFiMDRhMzhlMDhhMjRmZjRmOWZiYWQ1N2NjOGI2MGI1NDY3ODc0MDI0ZmJlMjQwYTNlODI3MWFlNmMzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1LJAM_BR9btHkHxPqPsRk6xLlB1pHHWNs2B1Wehv8Ys)

Thanks but again the result is given in Thousands (k) and not in the actual real amount. So the CSV files needs to be downloaded one by one to know the exact amount per each data. Not practical at all for statistics
