### ISSUE TITLE
Data Freeze to 2023-10-07

### ISSUE THREAD

**Issue by jjiglesiasg** [GIScience/ohsome-dashboard#32]
I am a former OSM-Analytics user, and due that they are shooting down their service, all data indicate to use ohsome suite. However it looks like the working data available is up to 2023-10-07, basically just 2 o 3 months more updated that the last one published by OSM-Analytics.

Could you please Update the working data? more than 3 months old is useless the data...

Thanks

**Comment by joker234** [comment]
Thank you for notifying us. The data of the ohsome dashboard (both OSM History Stats and OSM Quality Analyses) should normally be only up to 2 weeks old. If you open up https://dashboard.ohsome.org/#backend=ohsomeApi you should see the End date set to `2024-01-01T20:00:00Z` at the moment.

What query do you run? If you run a period query, you will always get periods starting from the start date. So if you have yearly periods, starting at `2007-10-08` your timestamps will always be `xxxx-10-08`.

More information can be found in the documentation of the underlying ohsome API: https://docs.ohsome.org/ohsome-api/stable/time.html

**Comment by jjiglesiasg** [comment]
I run a query using your link and the requested data (count) was between 2007-10-07 (default) up to 2024-01-18 (today) however the result is depicted up to 2023-12-07. The results are shown in k (thousands) 21.7k and the csv file show data up to 2023-12-08 with the amount of 21677 (count). 
However if I run a query with no start date and up to 2024-01-18 (again today) the CSV files show data results up to 2024-01-01 with an amount of 21751 (count)
Is that how it supposed to work?

**Comment by jjiglesiasg** [comment]
I run several queries. for the same parameter count (Places) in all 9 Departments (States) of my country, requesting data up to 2024-01-01 but the results logs show (k) data up to 2023-10-07 and in the CSV remains showing up to 2023-10-07 as well. 
The query do not include start date.
![Screenshot (153)](https://github.com/GIScience/ohsome-dashboard/assets/22849578/e938b945-67cb-4183-ab11-b5e50b6c67a8)
![Screenshot (152)](https://github.com/GIScience/ohsome-dashboard/assets/22849578/291d39f5-a5f5-4b5a-adbb-f8ab340eafa2)

**Comment by jjiglesiasg** [comment]
![Screenshot (154)](https://github.com/GIScience/ohsome-dashboard/assets/22849578/31e16496-8a01-43d0-8225-04db37520557)

CSV file for that example query.

**Comment by tyrasd** [comment]
>  Is that how it supposed to work?

Basically yes. Essentially, the timestamps for the results are always calculated from the start date, where the period is added until the end date is reached. If you clear the start field, the last used value (or the default start date if no date was manually set previously) will be used.

Here's what I would recommend to do if you want the most up to date data available:

> Choose a _Start_ date which matches the given _End_ date and the _Period_ of your choice, such that `Start + n * Period = End`. For example, if the `End` date is `2024-01-01` and you like `yearly` results, you could choose `2008-01-01` as the `Start` date: now you will get results for January 1 for every year, including the end date.
