### ISSUE TITLE
link only works for some topics

### ISSUE THREAD

**Issue by Gigaszi** [GIScience/ohsome-dashboard#44]
Currently, the link can be shared for the `Roads` and `Building Count` topics and the same indicators are selected directly and the calculation starts automatically. This is not the case for all other topics. The indicators are not selected and the filter is not displayed. 

Here, it is working: https://ohsome.org/apps/dashboard-test/#backend=oqtApi&topic=roads&adminids=-62400%2C-62695&indicators=currentness

Here, it is not working: https://ohsome.org/apps/dashboard-test/#backend=oqtApi&topic=supermarkets&adminids=-62400%2C-62695&indicators=currentness

**Comment by mcauer** [comment]
fixed with v1.3.1
